/*
===============================================================================
Financial Reconciliation Framework
03 - Financial Exposure Analysis
===============================================================================

Purpose:
    Quantify financial exposure generated by reconciliation exceptions
    and identify the exception categories representing the greatest
    financial risk.

SQL Engine:
    DuckDB
===============================================================================
*/

WITH reconciliation AS (
    SELECT *
    FROM read_csv_auto(
        'outputs/reconciliation_results.csv',
        header = true
    )
),

exceptions AS (
    SELECT *
    FROM reconciliation
    WHERE reconciliation_status <> 'MATCHED'
),

exposure_by_type AS (
    SELECT
        reconciliation_status AS exception_type,

        COUNT(
            DISTINCT transaction_id
        ) AS exception_count,

        SUM(
            COALESCE(financial_exposure_usd, 0)
        ) AS total_exposure_usd,

        AVG(
            COALESCE(financial_exposure_usd, 0)
        ) AS average_exposure_usd,

        SUM(
            CASE
                WHEN severity IN ('HIGH', 'CRITICAL')
                THEN COALESCE(financial_exposure_usd, 0)
                ELSE 0
            END
        ) AS material_exposure_usd,

        COUNT(
            DISTINCT CASE
                WHEN severity IN ('HIGH', 'CRITICAL')
                THEN transaction_id
            END
        ) AS material_exception_count,

        COUNT(
            DISTINCT CASE
                WHEN severity = 'CRITICAL'
                THEN transaction_id
            END
        ) AS critical_exception_count

    FROM exceptions

    GROUP BY reconciliation_status
),

total AS (
    SELECT
        SUM(total_exposure_usd)
            AS total_exception_exposure_usd
    FROM exposure_by_type
)

SELECT
    e.exception_type,
    e.exception_count,

    ROUND(
        e.total_exposure_usd,
        2
    ) AS total_exposure_usd,

    ROUND(
        100.0 * e.total_exposure_usd
        / NULLIF(t.total_exception_exposure_usd, 0),
        2
    ) AS exposure_share_pct,

    ROUND(
        e.average_exposure_usd,
        2
    ) AS average_exposure_usd,

    ROUND(
        e.material_exposure_usd,
        2
    ) AS material_exposure_usd,

    e.material_exception_count,
    e.critical_exception_count,

    DENSE_RANK() OVER (
        ORDER BY e.total_exposure_usd DESC
    ) AS exposure_rank

FROM exposure_by_type e
CROSS JOIN total t

ORDER BY
    exposure_rank,
    e.exception_type